# Generated by Django 6.0.2 on 2026-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PergerakanKolek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_upload', models.DateField()),
                ('rating_kolek', models.CharField(max_length=50)),
                ('rek_kredit', models.BigIntegerField()),
                ('cifid', models.CharField(max_length=50)),
                ('nama', models.TextField()),
                ('cabang', models.IntegerField()),
                ('plafond', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_akhir', models.DecimalField(decimal_places=2, max_digits=18)),
                ('hr_tungg_pokok', models.IntegerField()),
                ('hr_tungg_bunga', models.IntegerField()),
                ('kolek', models.IntegerField()),
            ],
            options={
                'ordering': ['tanggal_upload', 'rek_kredit'],
                'unique_together': {('rek_kredit', 'tanggal_upload')},
            },
        ),
    ]
