# Generated by Django 5.2.12 on 2026-03-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergerakankolek',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
