# Generated by Django 4.2.16 on 2026-03-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kolek', '0003_pergerakankolekkonvensional_and_syariah'),
    ]

    operations = [
        migrations.CreateModel(
            name='KantorCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('jenis', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Kantor Cabang',
                'verbose_name_plural': 'Kantor Cabang',
                'ordering': ['kode'],
            },
        ),
        # migrations.AddField(
        #     model_name='pergerakankolekkonvensional',
        #     name='nilai_wajar',
        #     field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        # ),
        # migrations.AlterField(
        #     model_name='pergerakankolekkonvensional',
        #     name='hr_tungg_margin',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AlterField(
        #     model_name='pergerakankolekkonvensional',
        #     name='hr_tungg_pokok',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AlterField(
        #     model_name='pergerakankolekkonvensional',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='pergerakankolekkonvensional',
        #     name='kolek',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.CreateModel(
            name='KantorCabangPembantu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('jenis', models.CharField(max_length=70)),
                ('cabang_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabang_pembantu', to='kolek.kantorcabang')),
            ],
            options={
                'verbose_name': 'Kantor Cabang Pembantu',
                'verbose_name_plural': 'Kantor Cabang Pembantu',
                'ordering': ['kode'],
            },
        ),
    ]
