# Generated by Django 4.2.16 on 2026-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolek', '0004_kantorcabang_pergerakankolekkonvensional_nilai_wajar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kantorcabang',
            name='is_aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kantorcabangpembantu',
            name='is_aktif',
            field=models.BooleanField(default=True),
        ),
    ]
