# Generated by Django 4.2.16 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolek', '0005_kantorcabang_is_aktif_kantorcabangpembantu_is_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='ckpn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='duedt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='nilai_wajar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='prodid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='prodnm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='strtdt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='tunggakan_bunga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankolekkonvensional',
            name='tunggakan_pokok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='ckpn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='duedt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='prodid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='prodnm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='strtdt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='tunggakan_bunga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pergerakankoleksyariah',
            name='tunggakan_pokok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pergerakankolekkonvensional',
            name='hr_tungg_margin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pergerakankolekkonvensional',
            name='hr_tungg_pokok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pergerakankolekkonvensional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pergerakankolekkonvensional',
            name='kolek',
            field=models.IntegerField(default=0),
        ),
    ]
