"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables dari file .env (Untuk keperluan Hosting/Server)
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY ditarik dari file .env agar tidak bocor di internet.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ksk#25ubz%m^+x(y5_5+41mj)vqxx9lvv2_uhpa&z%=#@l46y3')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG bernilai True bila di laptop, dan wajib diubah menjadi False di .env server.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS berisi domain/IP dari server, dipisahkan karakter koma.
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'kolek'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'kolektibilitas_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'admin123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'          # Bahasa Indonesia

TIME_ZONE = 'Asia/Jakarta'    # Sesuaikan timezone ke WIB

USE_I18N = True

USE_TZ = True

# LOGIN_URL → URL yang dituju saat user belum login dan mencoba akses halaman yang diproteksi.
# Kita arahkan ke halaman login bawaan Django admin (/admin/login/)
# sehingga tidak perlu membuat halaman login terpisah.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# WAJIB UNTUK HOSTING / SERVER: Tempat mengumpulkan semua file statis dari seluruh project.
# Jalankan perintah: python manage.py collectstatic - di server nantinya.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- SECURITY HARDENING (OWASP TOP 10) ---

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Session & Cookie Security
SESSION_COOKIE_HTTPONLY = True        # Prevent JS access to session cookie
SESSION_COOKIE_AGE = 1800             # Sessions expire after 30 minutes of inactivity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Clean session on browser close
CSRF_COOKIE_HTTPONLY = False          # Usually false so JS can read CSRF token, but keep it secure
CSRF_COOKIE_SECURE = not DEBUG        # Only send over HTTPS if in prod
SESSION_COOKIE_SECURE = not DEBUG     # Only send over HTTPS if in prod
SESSION_COOKIE_SAMESITE = 'Lax'       # Protection against CSRF
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Headers (Production only)
if not DEBUG:
    SECURE_SSL_REDIRECT = True        # Force HTTPS
    SECURE_HSTS_SECONDS = 31536000     # 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True # Prevent MIME sniffing
    SECURE_BROWSER_XSS_FILTER = True   # Enable browser XSS filter
    X_FRAME_OPTIONS = 'DENY'           # Prevent Clickjacking
    SECURE_REFERRER_POLICY = 'same-origin'