"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables dari file .env (Untuk keperluan Hosting/Server)
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY ditarik dari file .env agar tidak bocor di internet.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ksk#25ubz%m^+x(y5_5+41mj)vqxx9lvv2_uhpa&z%=#@l46y3')

# ─────────────────────────────────────────────────────────────
# KONFIGURASI CAPTCHA (django-simple-captcha)
# ─────────────────────────────────────────────────────────────
CAPTCHA_LENGTH = 7             # Jumlah karakter acak yang ditampilkan
CAPTCHA_IMAGE_SIZE = (220, 60) # Ukuran gambar captcha dalam piksel (lebar, tinggi)
CAPTCHA_LETTER_ROTATION = (-35, 35)  # Sudut rotasi tiap huruf agar susah dibaca bot
CAPTCHA_BACKGROUND_COLOR = '#f8fafc'  # Warna latar belakang gambar
CAPTCHA_FOREGROUND_COLOR = '#1e3a8a'  # Warna teks (biru Bank Sumut)
CAPTCHA_NOISE_FUNCTIONS = (    # Fungsi pembuat kebisingan visual
    'captcha.helpers.noise_arcs',  # Tambah busur garis
    'captcha.helpers.noise_dots',  # Tambah titik-titik
)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # Jenis: karakter acak
CAPTCHA_TIMEOUT = 5            # Masa berlaku kode (menit)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG bernilai True bila di laptop, dan wajib diubah menjadi False di .env server.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS berisi domain/IP dari server, dipisahkan karakter koma.
# Nilai default sudah mencakup IP dan domain server production.
# Di server, nilai ini di-override oleh .env (lihat file .env di server).
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '192.168.3.18,127.0.0.1,localhost,simolek.banksumut.co.id')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'kolek',
    'captcha',                         # django-simple-captcha: CAPTCHA teks gambar offline
    'django_otp',                      # OTP authentication
    'django_otp.plugins.otp_totp',     # TOTP plugin
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',      # OTP middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'kolektibilitas_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'admin123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'          # Bahasa Indonesia

TIME_ZONE = 'Asia/Jakarta'    # Sesuaikan timezone ke WIB

USE_I18N = True

USE_TZ = True

# LOGIN_URL → URL yang dituju saat user belum login dan mencoba akses halaman yang diproteksi.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# WAJIB UNTUK HOSTING / SERVER: Tempat mengumpulkan semua file statis dari seluruh project.
# Jalankan perintah: python manage.py collectstatic - di server nantinya.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- SECURITY HARDENING (OWASP TOP 10) ---

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Session & Cookie Security
SESSION_COOKIE_HTTPONLY = True        # Prevent JS access to session cookie
SESSION_COOKIE_AGE = 1800             # Sessions expire after 30 minutes of inactivity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Clean session on browser close
CSRF_COOKIE_HTTPONLY = False          # Usually false so JS can read CSRF token
CSRF_COOKIE_SECURE = not DEBUG        # Only send over HTTPS if in prod
SESSION_COOKIE_SECURE = not DEBUG     # Only send over HTTPS if in prod
SESSION_COOKIE_SAMESITE = 'Lax'       # Protection against CSRF
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Headers (Production only)
if not DEBUG:
    # NONAKTIFKAN redirect HTTPS karena server menggunakan HTTP biasa (Nginx tanpa SSL).
    # Jika diset True tanpa HTTPS di Nginx, Django akan terus redirect HTTP→HTTPS
    # secara loop yang menyebabkan 502 Bad Gateway.
    SECURE_SSL_REDIRECT = False
    # SECURE_PROXY_SSL_HEADER tetap disiapkan jika suatu saat HTTPS diaktifkan:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 0                                             # Nonaktif selama HTTP
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True                                  # Prevent MIME sniffing
    SECURE_BROWSER_XSS_FILTER = True                                    # Enable browser XSS filter
    X_FRAME_OPTIONS = 'DENY'                                            # Prevent Clickjacking
    SECURE_REFERRER_POLICY = 'same-origin'

# CSRF Trusted Origins — wajib untuk Django 4.x+ agar POST request (login, upload CSV)
# tidak ditolak 403 Forbidden. Sesuaikan dengan semua alamat yang ada di ALLOWED_HOSTS.
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    'http://192.168.3.18',                      # Akses via Nginx port 80
    'http://192.168.3.18:8000',                 # Akses langsung Gunicorn (testing)
    'http://simolek.banksumut.co.id',           # Domain production (HTTP)
    'https://simolek.banksumut.co.id',          # Domain production (HTTPS, jika aktif)
]